### ISSUE TITLE
`iedorep`: Re-write `recursive` option to expand sub-do-files in place for proper execution

### ISSUE THREAD

**Issue by luisesanmartin** [worldbank/ietoolkit#304] opened 2022-11-21 20:45 UTC
The command `iedorep dofile1.do` works as expected with these two do-files,

- dofile1.do
```{stata}
set obs 100
do "dofile2.do"
```
- dofile2.do
```{stata}
count
gen var5 = runiform()
```
returning this error message:
```{stata}
. iedorep try_iedorep.do
 
Processing: try_iedorep.do
Entering try_iedorep.do run....
Done with try_iedorep.do!

  +------------------------------------------------------+
  | Line |           Data |        Seed | Sort | Subfile |
  |------+----------------+-------------+------+---------|
  |    2 | ERROR! Changed | ERROR! Used |      |     Yes |
  +------------------------------------------------------+

. 

```
However, using the option `recursive` does not flag the reproducibility error in dofile2.do
```{stata}
. iedorep try_iedorep.do, recursive
 
Processing: try_iedorep.do
Entering try_iedorep.do run....
Done with try_iedorep.do!

  +------------------------------------------------------+
  | Line |           Data |        Seed | Sort | Subfile |
  |------+----------------+-------------+------+---------|
  |    2 | ERROR! Changed | ERROR! Used |      |     Yes |
  +------------------------------------------------------+
 
Errors detected in the following sub do-files; starting recursion.

  +--------------------------+
  | Line |              Path |
  |------+-------------------|
  |    2 | "try_iedorep2.do" |
  +--------------------------+
 
Processing: "try_iedorep2.do"
Entering "try_iedorep2.do" run....
Done with "try_iedorep2.do"!
 
No errors detected in sub do-files; recursion halted.

. 

```
Shouldn't line 2 of dofile2.do be flagged in a third table in the console?
Note that when I add the options `alldata`, `allsort`, and `allseed` there's a third table noting that the data changed in line 2 of dofile2.do
```{stata}
. iedorep try_iedorep.do, alldata allsort allseed recursive
 
Processing: try_iedorep.do
Entering try_iedorep.do run....
Done with try_iedorep.do!

  +------------------------------------------------------+
  | Line |           Data |        Seed | Sort | Subfile |
  |------+----------------+-------------+------+---------|
  |    1 |        Changed |             |      |         |
  |    2 | ERROR! Changed | ERROR! Used |      |     Yes |
  +------------------------------------------------------+
 
Errors detected in the following sub do-files; starting recursion.

  +--------------------------+
  | Line |              Path |
  |------+-------------------|
  |    2 | "try_iedorep2.do" |
  +--------------------------+
 
Processing: "try_iedorep2.do"
Entering "try_iedorep2.do" run....
Done with "try_iedorep2.do"!

  +----------------------------------------+
  | Line |    Data | Seed | Sort | Subfile |
  |------+---------+------+------+---------|
  |    2 | Changed |      |      |         |
  +----------------------------------------+
 
No errors detected in sub do-files; recursion halted.

. 

```

**Comment by bbdaniels** [comment] 2022-11-21 21:17
The issue is arising from the fact that `dofile2.do`, standing alone, has no reproducibility problems! When it is run a second time, there are no observations -- therefore it produces no data changes and does not draw any seeds, so no errors are caught. Obviously, that's not the way it will function in practice. Great catch on this.

I am not sure how to fix this right away, I need to think about it, as it is a memory management issue. It would require saving the Stata state right before sub-do-files are run, so that they can be restored at the recursive runs. I think I can figure it out with some time.

**Comment by bbdaniels** [comment] 2022-11-23 15:43
@luisesanmartin @kbjarkefur @luizaandrade What do you all think of this? It is rather challenging to resolve, as I am not aware of a way to freeze the entire Stata environment at a given point and reload it later, especially given the need of this command to clear nearly everything before each run. It is kind of fundamental here that each sub-do-file "stand alone". 

Is this something that can be sufficiently resolved by adding flags to the execution, or to the help-file? Or should we have a technical solution? For example, I could imagine tracking that an error was expected and then throwing an error if it is not detected in a sub-file run, therefore it must be this type of file structure.

@luisesanmartin I am assuming this type of thing hasn't caused any issues with passing globals down etc -- I can see how it would if they were coded clumsily or used (dynamically) as locals, since globals are not wiped between runs.

**Comment by bbdaniels** [comment] 2022-11-23 16:02
Proposed partial fix in cc562cb5ae8fa8847f331138c4205a2cf4902af3. Result here is now:

```
  +---------------------+
  | Line |         Path |
  |------+--------------|
  |    2 | "dofile2.do" |
  +---------------------+
 
Processing: "dofile2.do"
Entering "dofile2.do" run....
Done with "dofile2.do"!
 
No errors detected in sub do-files; recursion halted.
 
!!------ WARNING ------!!
An error was expected in this sub do-file but none was found.
  This can occur when sub do-files are not independent.
  Check that this sub do-file does not depend on the calling file.
  This includes both the data state and global macros;
    the data is reset on each run, but macros are not.
 
something that should be true of your data is not
r(459);
```

**Comment by luisesanmartin** [comment] 2022-12-05 21:52
@bbdaniels have you considered saving the Stata state before the run of a sub do-file as a tempfile? I understand the challenge would be that running iedorep on a sub do-file would delete tempfiles out of the memory, but then it's probably possible to modify it so when it's run recursively for a sub do-file it does not do that. I think this would be somewhat similar to the change you introduced for do-files using `clear` or `clear all` when you found a way to control what to delete from the memory so the command would work.

I also see that these might be challenging to implement. For v1 I think it's okay to go ahead with the change of https://github.com/worldbank/ietoolkit/commit/cc562cb5ae8fa8847f331138c4205a2cf4902af3. @kbjarkefur , @luizaandrade do you have any thoughts?

**Comment by bbdaniels** [comment] 2022-12-08 13:50
@kbjarkefur, this is a super thorough and useful comment, and I think it is exactly on the nose about the underlying issue and is a very useful solution. However! I do not have time for it now. Are you OK with releasing 1.0 as it is, or with minor modifications to the current error message / results report? Then I will come back and work on implementing something like this in the new year.

**Comment by kbjarkefur** [comment] 2022-12-08 15:10
The compromise solution I am suggesting is to drop everything related to the recursive call, and add a note in help file that sub-dofiles is a feature that will come. That should be quick

**Comment by bbdaniels** [comment] 2022-12-08 15:35
I have left it undocumented instead so we can still use it in the released version for testing. Done in 4976cd5780f98f93196b55a87a4307fac2a2fff3

**Comment by kbjarkefur** [comment] 2022-12-08 15:39
What about not using the word "error" for mismatches?

**Comment by luisesanmartin** [comment] 2022-12-14 22:32
@kbjarkefur thanks for the review and comments. I think the second solution your propose in [your comment](https://github.com/worldbank/ietoolkit/issues/304#issuecomment-1342681506) is the one that would work best. I'm leaving this issue open so that we remember that it's pending and will approve #261 so v1 will be published

**Closed** 2023-11-03 17:19 UTC
Labels: command review
