### ISSUE TITLE
iebaltab: weight option is not working

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/ietoolkit#171] opened 2018-11-07 17:51 UTC
The marksample in line 86 is causing an invalid syntax error when the option weight() is used in iebaltab.

**Comment by kbjarkefur** [comment] 2018-11-08 22:35
This is resolved but not yet published. We will close this issue once the fix is published on SSC. This will be as soon as possible as the issue is labeled **major bug**

**Closed** 2018-11-19 18:33 UTC
Labels: major bug, resolved but not yet published
